from enum import Enum

class EpistemicStatus(str, Enum):
    OBSERVED = "OBSERVED"
    DERIVED = "DERIVED"
    INFERRED = "INFERRED"
    MISSING_NOT_OBSERVED = "MISSING_NOT_OBSERVED"
    NOT_APPLICABLE = "NOT_APPLICABLE"
    UNRESOLVED = "UNRESOLVED"
    WITHHELD_FOR_EVALUATION = "WITHHELD_FOR_EVALUATION"
